### ISSUE TITLE
Variable names in generated AADL files

### ISSUE THREAD

**Issue by svenTeum** [OpenAADL/fmu2aadl#1]
I'm using some FMUs generated by Amesim tool. When running fmu2aadl, I get the corresponding AADL files.
The problem is that the FMUs have input/output names that contain some special characters, like for example:
_pin@expseu__
In that way, I must manually edit the variable names in fmu_name.aadl and fmu_name_wrapper.c to something like
_pinexpseu_
(otherwise Ocarina won't compile the model using those FMUs)

Because of that manually editing, I'm not sure if some other errors I get are related to that.

Could it be possible for _fmu2aadl_ to parse that kind of variable names?

**Comment by yoogx** [comment]
I think the right path would be to escape those names the proper way. Do you have a list special characters ? beyond @ and _ ?

Note I did not test Amesim FMUs. Would it make sense for you to contribute a basic FMU that I can integrate in my test suite ?

**Comment by svenTeum** [comment]
Thanks, I will see if I can send you an FMU from Amesim (BTW how can I send you a file?)
In my case I had to replace only those two characters.

Another issue with Amesim FMUs is that they generate a specific label in ModelDescription.xml that is not parsed well when running Ocarina so I also have to edit the xml file as a previous step to building with Ocarina. But maybe I should open a different issue for that.

**Comment by yoogx** [comment]
I think you can do a pull request to send files, in particular if there are issues in ModelDescription.xml

You may have reviewed the code, it is basic and goes straight to the point. Having more FMUs to test would be helpful

**Comment by svenTeum** [comment]
I'm attaching an example file here:
[ABouncingBall.zip](https://github.com/OpenAADL/fmu2aadl/files/2240877/ABouncingBall.zip)

Ocarina can compile an AADL file that uses that kind of FMU after removing the characters from the variables. Also, about the _ModelDescription.xml_, unless you remove this kind of lines:
`<Annotations><Tool name="Amesim"><VarAnnot index="1"/></Tool></Annotations>`
running the Ocarina build executable will show the following:
```
Parser error. Depth wrong after parsing sub-tree for Tool.
Segmentation fault
```
Also please note that I tested an FMU from Amesim with fmusdk and it worked with no parsing errors.

**Comment by yoogx** [comment]
Thanks for this FMU. I see the bug. Unfortunately, you won't go further with this kind of FMU since it as local or parameter variables, whereas the FMU2AADL script expects input/output.
Can you provide one ?

**Comment by svenTeum** [comment]
The following FMU has 1 input and 1 output:
[ABouncingBall_v2.zip](https://github.com/OpenAADL/fmu2aadl/files/2243980/ABouncingBall_v2.zip)
