### ISSUE TITLE
Output file result.csv missing

### ISSUE THREAD

**Issue by svenTeum** [OpenAADL/fmu2aadl#2]
I would like to know about the result.csv file generated when running the _moonlanding_ example (also valid for _rosace_ one).

The output seems to be OK but the result.csv file only contains one line of data. Is it possible for the result.csv file to get all the data that is shown via console output?

**Comment by yoogx** [comment]
I just checked with the provided Dockerfile, and I get all values in result.cvs. How did you compile this example? 

I can display data on stdout if needs be, I was not convinced it was useful. I'll try to schedule the implementation of this feature in my slack time, I'm currently in vacation

**Comment by svenTeum** [comment]
I was testing with Debian 9, using make build and make run commands.
I just tested with docker (running
`docker build -t ocarina/fmi .`
then
`docker run -t -i ocarina/fmi bash`
and finally _make build_ and _make run_ into _moonlander_ folder in docker environment) but I get the same results:
```
ocarina@505b27801051:~/fmu2aadl/examples/moonlanding$ cat result.csv
time,_block_jacobian_check,_block_jacobian_check_tol,_block_solver_experimental_mode,_block_solver_profiling,_cs_experimental_mode,_cs_rel_tol,_cs_solver,_cs_step_size,_enforce_bounds,_events_default_tol,_events_tol_factor,_iteration_variable_scaling,_le_sparse_jacobian_threshold,_log_level,_nle_active_bounds_mode,_nle_brent_ignore_error,_nle_jacobian_calculation_mode,_nle_jacobian_finite_difference_delta,_nle_jacobian_update_mode,_nle_solver_check_jac_cond,_nle_solver_default_tol,_nle_solver_exit_criterion,_nle_solver_max_iter,_nle_solver_max_iter_no_jacobian,_nle_solver_max_residual_scaling_factor,_nle_solver_min_residual_scaling_factor,_nle_solver_min_tol,_nle_solver_regularization_tolerance,_nle_solver_step_limit_factor,_nle_solver_tol_factor,_nle_solver_use_last_integrator_step,_nle_solver_use_nominals_as_fallback,_rescale_after_singular_jac,_rescale_each_step,_residual_equation_scaling,_runtime_log_to_file,_time_events_default_tol,_use_Brent_in_1d,_use_jacobian_equilibration,_use_newton_for_brent,a,altitude,der(altitude),earth_moon_distance,earth_sun_distance,g,gravity,mass,der(mass),massLossRate,mass_earth,mass_moon,mass_sun,radius_earth,radius_moon,radius_sun,thrust,v,velocity,der(velocity)
0,0,1e-06,0,0,0,1e-06,1,0.001,1,1e-10,0.0001,1,-1,3,0,0,0,1.490116119384766e-08,2,0,1e-10,3,100,10,10000000000,1e-10,1e-12,-1,10,0.0001,1,1,1,0,1,0,2.220446049250313e-14,1,0,1,60000,60000,-2000,384400000,1499822700000000,6.672e-11,-1.525726300005082,75000,-0,2.77e-05,5.972e+24,7.38e+22,1.9891e+30,6371000,1738000,696000000,0,-2000,-2000,-1.525726300005082
```

Only a line for time = 0 it seems

**Comment by yoogx** [comment]
OK, got it. I had a old docker container with the code
I got rid of the result.csv file as part of this commit
https://github.com/OpenAADL/fmu2aadl/commit/62d9ae2dbb2b6b222376849656231634b2fa3a77

I'm restoring this

**Comment by yoogx** [comment]
This should be restored, please confirm and close this issue

**Comment by svenTeum** [comment]
Yes, it works now. Thank you.
