### ISSUE TITLE
FMU input/outputs matching AADL reference keywords

### ISSUE THREAD

**Issue by svenTeum** [OpenAADL/fmu2aadl#3]
If I have for example an FMU with an input called _reference_, fmu2aadl generates the corresponding AADL files but the name of the input is still _reference_

Then the resulting model can't be compiled with Ocarina since _reference_ is an AADL keyword and the file parsing fails.

fmu2aadl may at least show a warning about that issue so the user can modify the FMU.

**Comment by yoogx** [comment]
You're right, there should be a mechanism to explicitly forbid this. I see two options (related to your other issues)

a) forbid the inclusion of such FMU. Easy, but worthless, as we should not reject FMU based on such name

b) propose a rewrite strategy for names to avoid such situation. An easy option would be simply to have as a rule to prefix every name from the FMU with a prefix like

FMI_<in|out>_param_<original_name>

I'll implement b) when time permits.
