### ISSUE TITLE
Installation errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by Blissqiu** [OpenAADL/fmu2aadl#7]
![image](https://user-images.githubusercontent.com/31772665/74103428-cd9e2c80-4b00-11ea-86bc-78a063163f04.png)
When I input the command of make run, the above error is generated.
I'm not very familiar with makefile files, so I can't solve this problem by myself.
I use Ubuntu 18.04 system. The environment configuration is installed step by step according to the docker file provided. Ocarina and fmu2aadl are both running normally

**Comment by yoogx** [comment]
Did you run "make" or "make build" first ? what is the output ?

**Comment by Blissqiu** [comment]
i have aleardy run "make build" commmand.
When I run this command, the results are as follows：
![QQ图片20200210123319](https://user-images.githubusercontent.com/31772665/74121344-22759c00-4c02-11ea-96f6-8190b02c6b7e.png)
![QQ图片20200210123325](https://user-images.githubusercontent.com/31772665/74121346-23a6c900-4c02-11ea-890e-c14b1a56adb4.png)
![3](https://user-images.githubusercontent.com/31772665/74121348-24d7f600-4c02-11ea-9d39-bac8457baf40.png)
![3](https://user-images.githubusercontent.com/31772665/74121349-26092300-4c02-11ea-8057-077d82303946.png)
![4](https://user-images.githubusercontent.com/31772665/74121351-27d2e680-4c02-11ea-9d88-9b791d245375.png)
![5](https://user-images.githubusercontent.com/31772665/74121354-2acdd700-4c02-11ea-943e-5c4ae38ae9c2.png)
![6](https://user-images.githubusercontent.com/31772665/74121359-2c979a80-4c02-11ea-881c-905669375c50.png)
![image](https://user-images.githubusercontent.com/31772665/74121369-39b48980-4c02-11ea-9f0b-1ab5aaffb6dc.png)

At first, I thought it was character encoding that caused the problem, but it wasn't

**Comment by yoogx** [comment]
Instead of "make run", type "./moonlanding_sys_impl/lander/lander" 
The binary has been correctly generated, but does not execute

**Comment by Blissqiu** [comment]
![image](https://user-images.githubusercontent.com/31772665/74210344-52867300-4cc6-11ea-9ee6-9fc604597475.png)
i try to it,but i did not find the file of result.csv

**Comment by yoogx** [comment]
Please provide more details. How long did the program run? If you check the source code; it should display some elements.So it is surprising you do not see anything ...

The fact that make returns an error is the indication of an internal crash. Are you using a 64 bits Ubuntu?

**Comment by Blissqiu** [comment]
My ubuntu system is 64-bit

Sorry, I tried other methods, but I still didn't produce the result.csv file, and worse, I couldn't find the problem.

I see the @ sign after the run command in the makefile, and it's still invalid
![image](https://user-images.githubusercontent.com/31772665/74214201-70100880-4cd7-11ea-8a53-32f45eef3272.png)

When I went straight into this directory and tried./lander still didn't generate the target file, but there was one more (fmu_moonland.fmu)
![image](https://user-images.githubusercontent.com/31772665/74214214-7e5e2480-4cd7-11ea-83c9-ea84856b2c6c.png)

I wanted to ask you what directory the result file was in when you ran it successfully, and what your versions of GCC and g++ are.
![image](https://user-images.githubusercontent.com/31772665/74214233-90d85e00-4cd7-11ea-9dd0-6d393aefcc5c.png)

**Comment by yoogx** [comment]
So you have an invalid setup.

Under mine, "make run" executes the system, you see a collection of numerical values printed and the CSV file is generated. I use GCC 8.3.0 from Debian 10

If the @ sign bothers you in the makefile, you may simply remove it. It is purely cosmetic

**Comment by Blissqiu** [comment]
Sorry for the late reply.
I tried to update the version of GCC，but it failed.
I think that's probably the problem, I'm thinking of other ways to update the version of GCC, the whole process might be a little bit slow. In case I bother you, I'll close the problem and try again to see if I can fix it when I do a successful update.
