### ISSUE TITLE
Compilation on debian 10

### ISSUE THREAD

**Issue by Blissqiu** [OpenAADL/fmu2aadl#8]
i have tried the new gcc,but it was not effecitive,Can you send the moonlanding result.csv directly to me？

**Comment by Blissqiu** [comment]
I also tried to install debian10, but many of the related software written in dockerfile in FMU2aadl could not be installed.

**Comment by yoogx** [comment]
I updated the docker file to debian 10.

I confirm it builds fine; and could run the moonlander from within the docker file.
There is a crash for ROSACE in docker but not in my debian 10 VM. I will not investigate it at this stage.
